# Generated by Django 2.2.1 on 2019-06-18 08:54

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickName', models.CharField(max_length=20, null=True, verbose_name='昵称')),
                ('userAddress', models.CharField(max_length=35, null=True, verbose_name='住址')),
                ('userGender', models.CharField(max_length=10, null=True, verbose_name='性别')),
                ('userPhone', models.CharField(max_length=15, null=True, verbose_name='手机号')),
                ('userIdcard', models.CharField(max_length=50, null=True, verbose_name='身份证号')),
                ('userPassword', models.CharField(max_length=50, null=True, verbose_name='密码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否禁止')),
            ],
            options={
                'verbose_name': '用户账户',
                'verbose_name_plural': '用户账户',
                'db_table': 'user_table',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ValidatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=25)),
                ('imei', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=10)),
                ('sign', models.CharField(max_length=65)),
                ('key', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seed', models.CharField(max_length=65)),
            ],
            options={
                'verbose_name': '用户请求日志',
                'verbose_name_plural': '用户请求日志',
            },
        ),
    ]
