# Generated by Django 2.2.1 on 2019-05-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=25)),
                ('imei', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=10)),
                ('sign', models.CharField(max_length=65)),
                ('key', models.CharField(max_length=30)),
                ('hadPast', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seed', models.CharField(max_length=65)),
            ],
        ),
    ]
