# Generated by Django 2.2.1 on 2019-05-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validatepost',
            options={'verbose_name': '用户请求日志', 'verbose_name_plural': '用户请求日志'},
        ),
    ]
