# Generated by Django 2.2.1 on 2019-06-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_auto_20190618_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='激活状态'),
        ),
    ]
