# Generated by Django 2.2.1 on 2019-05-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0005_auto_20190528_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_idcard',
            field=models.CharField(max_length=50, null=True, verbose_name='身份证号'),
        ),
    ]
