# Generated by Django 2.2.1 on 2019-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0007_remove_validatepost_hadpast'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatepost',
            name='secondSeed',
            field=models.CharField(default=0, max_length=65),
            preserve_default=False,
        ),
    ]
